### PR TITLE
Fixed a bug raising an exception if existing field contains a null value

### PR DESCRIPTION
**Pull request by tlode**
Replaced isset() calls with array_key_exists(), which allows testing and fetching fields containing a null value.

### CODE REVIEW

**Comment by chanmix51** [comment]
Thank you :+1:

**Comment by mvrhov** [comment]
ake is a lot slower than isset. If the code is called a lot the difference is visible.
The suggestion would be to call `isset(foo) || ake(foo)` see symfony/symfony#8907

**Comment by chanmix51** [comment]
nice ! :+1:

**Comment by chanmix51** [comment]
Done in 93ae9ff.

**Pull request merged**
